### ISSUE TITLE
unary operator expected

### ISSUE THREAD

**Issue by camjac251** [zertrin/duplicity-backup#106]
Got this when running sudo /usr/local/src/duplicity-backup/duplicity-backup.sh -c /etc/duplicity-backup/duplicity-backup.conf -b
It backed up then before it finished it says that, don't think it stopped the backup process though

/usr/local/src/duplicity-backup/duplicity-backup.sh: line 847: [: ==: unary operator expected

**Comment by zertrin** [comment]
Hi, thanks for reporting it, indeed the backup works, but there was a typo in an if test in the last pull request. I just fixed it and pushed the fix to `dev` and `master`.
