### ISSUE TITLE
How can I get duplicity-backup to use lftp's FTPS? (ftp over ssl, not sftp)

### ISSUE THREAD

**Issue by vx28643** [zertrin/duplicity-backup#110]
Hello. How can I get duplicity-backup to use lftp's FTPS? (ftp over ssl, not sftp)

I have tried adding "set ftp:ssl-force true" to /etc/lftp.conf but did not seem to enforce ssl unless I am running lftp directly. Can I configure lftp options somewhere in duplicity-backup's config?

As I only have FTPS access to my target machine I really would like to get this working...

Thank you for your thoughts :)

**Comment by zertrin** [comment]
Hi @vx28643 !

duplicity-backup.sh is a wrapper for duplicity, which in turn takes care of connecting to the backend (in your case FTPS). You need to configure correctly the `DEST` parameter for duplicity.

Did you try `DEST="ftps://user[:password]@other.host[:port]/some_dir"` ?

Refer to the official documentation for more information: http://duplicity.nongnu.org/duplicity.1.html#sect7
I didn't know that there is an alternative URL scheme for using lftp (`lftp+ftp://....`) and I have no experience with it. 

As a reminder, I am in no way affiliated to duplicity, only to this bash wrapper. Your question seems to concern duplicity, so I will close the issue. If using `ftps://` doesn't work, look for help on the mailing list of duplicity (http://lists.nongnu.org/mailman/listinfo/duplicity-talk). I suggest to try to get duplicity working before using duplicity-backup.sh. If you can make duplicity working but not duplicity-backup.sh than feel free to reopen this issue :wink: 

Thanks for considering duplicity-backup.sh and I hope you'll find the solution to your problem!

**Comment by vx28643** [comment]
Thank you very much. You helped me hunt down the issue. Seems duplicity ignores the lftp.conf and sets its own settings in the [lftpbackend.py](https://github.com/henrysher/duplicity/blob/master/duplicity/backends/lftpbackend.py) backend.

`ftps://` was indeed correct, but in the end, I actually needed to use `ftpes://` for my actual situation. Perhaps these should be added to the list of possible destinations in the duplicity-backup.conf.example?

Anyway, thanks for making this great Duplicity wrapper!
