### ISSUE TITLE
How to deal with incomplete backup sets

### ISSUE THREAD

**Issue by hameno** [zertrin/duplicity-backup#123]
Hi,
while trying to fix a connectivity issue with our backup server I had to interrupt a few backups. Now duplicity shows a warning on each run:
```Warning, found incomplete backup sets, probably left from aborted session```
Does this wrapper script support cleaning/removing the incomplete sets? (I know I can manually clean that up by calling duplicity clean <remote-path>)

**Comment by zertrin** [comment]
Hi,
not currently, but I guess that would be a nice addition to the script. Shouldn't be too hard to implement. Will add this to the categories _enhancement_ and _patch welcomed_ and to my todo list.

Thanks for the feedback!

**Comment by lechup** [comment]
@hameno I've added #131 that should do the trick...

**Comment by zertrin** [comment]
Thanks again @lechup for your contribution! I merged it in develop, and needs a bit of testing but it looks pretty good.

I'm closing the issue for now, feel free to reopen if needed :wink:
