### ISSUE TITLE
Cannot access '/proc...

### ISSUE THREAD

**Issue by raciasolvo** [zertrin/duplicity-backup#146]
stable version, CentOS 7
Run:
`./duplicity-backup.sh -f -c <....conf>`
Have warning and errors:
```
Warning: Option --include-globbing-filelist is pending deprecation and will be removed in a future release.
--include-filelist and --exclude-filelist now accept globbing characters and should be used instead.
du: cannot access ‘/proc/7811/task/7811/fd/4’: No such file or directory
du: cannot access ‘/proc/7811/task/7811/fdinfo/4’: No such file or directory
du: cannot access ‘/proc/7811/fd/4’: No such file or directory
du: cannot access ‘/proc/7811/fdinfo/4’: No such file or directory

```
Backup created without errors.

**Comment by zertrin** [comment]
Hi, thanks for reporting.

The warning is being tracked in issue #136.

The `/proc` errors should have disappeared with the latest version of the script (v1.2+) (see https://github.com/zertrin/duplicity-backup/commit/0f901f4f78a148a86026b96b791a1d689849d8ab).

However when using include-exclude-filelists, du can't calculate correctly, this is known and tracked in issue #101.

I'll close this issue as duplicate, feel free to reopen if you think your issues are not covered by the aforementioned bugs.
