### ISSUE TITLE
Add support for AWS Glacier

### ISSUE THREAD

**Issue by rubyvrooom** [zertrin/duplicity-backup#15]
This would drop the "cost of ownership" significantly.

Glacier = $0.010 per GB/month
$0.055 per 1,000 requests

S3 =       $0.140 per GB/month
$0.011 per  1,000 requests

http://aws.amazon.com/glacier/

**Comment by arichiardi** [comment]
Sorry to beat a dead horse, but given that duplicity seems not to have support or Glacier, which make sense actually, should this script provide it?

It would be awesome at list to generate the commands necessary to create lifecycle rules that one could execute himself and warn/mark when one archive resides in glacier.

We handle time and lifecycle rules already...other ideas and hints are welcome, I would love to have something like [duply](https://sedden.github.io/blog/2015/11/11/backup-to-amazon-s3-glacier-with-duplicity).

Maybe we can reopen this issue @zertrin?

**Comment by zertrin** [comment]
Sorry but I think this is out of scope for this script.

Glacier is really a different approach to file storage and there is no easy way of automating all of it, even less so in a simple bash script.

Implementing all the needed logic to manage Glacier already looks like the job for a dedicated tool (and I'm persuaded that there is some already available).

This script only cares about facilitating usage of duplicity. As long duplicity doesn't support Glacier as a backend (and I don't see it coming any time soon), there is nothing we can do here.

The example you linked just uses S3 buckets with a manually defined lifecycle rule _"Configuration: Archive to the Glacier Storage Class 1 days after the object's creation date."_. You can do the same already with our wrapper, that's just configuration on AWS side.
