### ISSUE TITLE
Possible issue with Cleanup Option

### ISSUE THREAD

**Issue by smcgrat** [zertrin/duplicity-backup#177]
I might be, (probably am), doing this wrong or miss-interpreting something here, so my apologies if that is the case and I will be grateful if you can point out my errors.

I'm trying to back up a large amount of data, in the region of 30TB. The first attempt to do that failed because the root system disk, (which is quite small), filled up with temporary files and the backups where left in an unclean state on the remote host. I tried to clean those up and came across this possible issue.

Running ``duplicity-backup.sh -e`` gave the following error in the logs:
```
--------    START DUPLICITY-BACKUP SCRIPT for server.fqdn   --------

Attempting to acquire lock /var/log/duplicity/backup.lock
successfully acquired lock.
-------[ Cleaning up Destination ]-------

Attempt 1 failed. BackendException: Error running 'rsync -e 'ssh  -oBatchMode=yes '  serverbackup@backuphost.fqdn:/data/server/': returned 255, with output: 

Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(605) [Receiver=3.0.9]

Attempt 2 failed. BackendException: Error running 'rsync -e 'ssh  -oBatchMode=yes '  serverbackup@backuphost.fqdn:/data/server/': returned 255, with output: 

Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(605) [Receiver=3.0.9]

Attempt 3 failed. BackendException: Error running 'rsync -e 'ssh  -oBatchMode=yes '  serverbackup@backuphost.fqdn:/data/server/': returned 255, with output: 

Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(605) [Receiver=3.0.9]

Attempt 4 failed. BackendException: Error running 'rsync -e 'ssh  -oBatchMode=yes '  serverbackup@backuphost.fqdn:/data/server/': returned 255, with output: 

Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(605) [Receiver=3.0.9]

Cleanup complete.
---------    END DUPLICITY-BACKUP SCRIPT    ---------

Email notification sent to ...
Removing lock. Exit code: 0
```

Looked to me like the method I was using to authenticate to the backup repository in the ``duplicity-backup.conf`` wasn't being respected:
```
STATIC_OPTIONS="--ssh-options="-oIdentityFile=/root/.ssh/backupserver/id_rsa" --volsize=1000 --tempdir=/home/support/duplicity-tempdir"
```

Working around that, (I changed ``duplicity-backup.sh`` slightly, more below), I then ran into another problem. I have configured duplicity not to encrypt backups, but that didn't seem to be being respected either. I was being prompted for a GPG key even though ``duplicity-backup.conf`` has ``ENCRYPTION='no'`` set. Here's what I saw in the log:
```
--------    START DUPLICITY-BACKUP SCRIPT for server.fqdn   --------

Attempting to acquire lock /var/log/duplicity/backup.lock
successfully acquired lock.
-------[ Cleaning up Destination ]-------

Local and Remote metadata are synchronized, no sync needed.
Cleaning up previous partial cleanup backup set, restarting.
Warning, discarding last backup set, because of missing signature file.
Warning, found incomplete backup sets, probably left from aborted session
Last full backup date: Tue Apr 17 15:54:35 2018
Cannot use empty passphrase with symmetric encryption!  Please try again.
Cannot use empty passphrase with symmetric encryption!  Please try again.
Cleanup complete.
---------    END DUPLICITY-BACKUP SCRIPT    ---------

Email notification sent to 
Removing lock. Exit code: 0
```

I ran a ``duplicity-backup.sh -e -d`` to get the commands that where being run and saw that the following was being run:
```
/usr/bin/duplicity cleanup -v3 --ssh-options=-oIdentityFile=/root/.ssh/backupserver/id_rsa --volsize=1000 --tempdir=/home
/support/duplicity-tempdir --force rsync://serverbackup@backupserver.fqdn//data/server/```
```

When I manually ran the above and added the ``--no-encryption`` flag the cleanup started. It is still going because it is massive.

I modified the ``duplicity-backup.sh`` slightly as follows.
1. Looks like ``STATIC_OPTIONS`` is being set to just ``--force`` when the cleanup flag is supplied. I changed it to preserve the already set static options.
2. Instead of calling ``duplicity_cleanup_failed`` I changed it to call ``duplicity_cleanup`` instead. **Note, this has not been tested yet**. At the time of writing the cleanup using just duplicity instead of duplicity-backup.sh is running and I don't want to interrupt it.

Here's the patch diff of the modifications.

```
$ diff -u duplicity-backup.sh Modified-duplicity-backup.sh 
--- duplicity-backup.sh 2016-09-03 16:45:16.000000000 +0100
+++ Modified-duplicity-backup.sh        2018-05-18 16:34:02.414903360 +0100
@@ -836,12 +836,12 @@
     OPTION="cleanup"
 
     if [ -z "${DRY_RUN}" ]; then
-      STATIC_OPTIONS="--force"
+      STATIC_OPTIONS="${STATIC_OPTIONS} --force"
     fi
 
     echo -e "-------[ Cleaning up Destination ]-------\n" >> "${LOGFILE}"
     setup_passphrase
-    duplicity_cleanup_failed
+    duplicity_cleanup
 
     echo -e "Cleanup complete." >> "${LOGFILE}"
   ;;

```

I has occurred to me that I might be misinterpreting what should be being done with ``duplicity_cleanup_failed``, I haven't looked at the code closely at all. So please let me know if I am.

Thanks.

Sean

(edited coz I find markup hard :-( )

**Comment by smcgrat** [comment]
Quick update, running ``duplicity-backup.sh -c /etc/duplicity-backup.conf -e`` with the above patch now seems to work, I think. This is the output:

```
--------    START DUPLICITY-BACKUP SCRIPT for server.fqdn   --------                                        
                                                                                                                    
Attempting to acquire lock /var/log/duplicity/backup.lock                                                           
successfully acquired lock.                                                                                         
-------[ Cleaning up Destination ]-------                                                                          
                                                                               
----------------[ Duplicity Cleanup ]----------------                            
Local and Remote metadata are synchronized, no sync needed.                                                         
Warning, discarding last backup set, because of missing signature file.            
Warning, found incomplete backup sets, probably left from aborted session                                           
Last full backup date: Tue Apr 17 15:54:35 2018                                                                     
No old backup sets found, nothing deleted.                                                                          
                                                                                                                    
Cleanup complete.                                                            
---------    END DUPLICITY-BACKUP SCRIPT    --------- 
```

That was after manually cleaning the remote repository though, so there where no backups to be cleaned by ``duplicity-backup.sh``.

Thanks.

Sean

**Comment by zertrin** [comment]
Thanks for the report and the feedback 😄 

I think only the first part of your patch would be needed, indeed `STATIC_OPTIONS` were forgotten when this function was added.

The `duplicity_cleanup_failed` was specifically introduced for the action `-e` in pull request #131 and seemed to be aimed at the kind of recovery you had to do (unclean backups).

The other one `duplicity_cleanup` is meant for routine usage after successful backup.

I'm not sure if I should include the second modification of your patch. (In fact I'm not sure myself what are the difference between them).

**Comment by smcgrat** [comment]
Hi zertrin,

Thanks for that. I see the point of ``duplicity_cleanup_failed()`` now alright.

It's ``eval`` line is missing the ``"${ENCRYPT}"`` variable though, thus why it failed to work for me, I'm not using encryption on the source. Can I request that that variable be added to to the function please?

Best

Sean

**Comment by zertrin** [comment]
Ah yeah that makes sense. Thanks for figuring it out. Will see to fix it soon. Thanks again!

**Comment by zertrin** [comment]
I've implemented the changes, it's now in the dev branch and in v1.6.0. Let me know if that solves the issue for you now.

**Comment by smcgrat** [comment]
Thanks very much, those changes look good. I won't have a chance to test properly for a while unfortunately, sorry about that. I'll get back when I can.
