### ISSUE TITLE
Feature Request: Only backup when connected to a whitelist of networks

### ISSUE THREAD

**Issue by karlseguin** [zertrin/duplicity-backup#178]
Don't run  unless you're connected to a known network. I use this to make sure I'm not backing up on a public wifi, which can have limits.

Right now, I just put:

```
SSID=$(iwgetid -r)
if [[ $SSID != "HOME_SSID" ]]; then
  echo "Connected to unknown network: ${SSID}"
  exit 1;
fi
```

at the top of the script. But having this as a configurable list would be better.

**Comment by zertrin** [comment]
Hi, thanks for the suggestion but this is a really specific wish and I consider it out of scope for this project.

This is better suited for a wrapper script around calling duplicity-backup.sh like so:

```bash
#!/bin/bash

SSID=$(iwgetid -r)
if [[ $SSID != "HOME_SSID" ]]; then
  echo "Connected to unknown network: ${SSID}"
  exit 1;
fi

/path/to/duplicity-backup.sh -c /path/to/config_file
```

**Comment by karlseguin** [comment]
Ok. Thanks for considering. Maybe someone googling will find this issue and at least learn how to implement it themselves.
