### ISSUE TITLE
How to restore the last known backup?

### ISSUE THREAD

**Issue by radhe** [zertrin/duplicity-backup#184]
Hello 

I am trying to restore the last available backup. 

`duplicity-backup.sh -c backup.conf -t60D --restore-file name.pdf /tmp/`

Can you please advice on how to use the --time option to restore the last available backup? 

Thanks.

**Comment by zertrin** [comment]
Sorry for the late reply, I have been unavailable for the last couple of months.

For the time format please refer to the duplicity documentation since the value is directly passed to duplicity as is.
