### ISSUE TITLE
Archives Sizes 200MB

### ISSUE THREAD

**Issue by jeanmigaillard** [zertrin/duplicity-backup#185]
Hello,
I would like to know if there is the possibility of changing the size of the archives.
In fact they are currently 200mb and it makes a lot of files and lengthen the time of execution.
Thank you for your work, cordially,

**Comment by zertrin** [comment]
Yes you can, just pass the appropriate duplicity option (see duplicity documentation) in the static options variable.

**Comment by jeanmigaillard** [comment]
Thank you for you precise response.
Cordially,
