### ISSUE TITLE
How to restore after complete data loss

### ISSUE THREAD

**Issue by mindrunner** [zertrin/duplicity-backup#190]
How do I proper restore assuming I lost all my data and only have the encrypted backup files. In specific, I want to restore without having my config file and without going through all the config options I do not need for a restore.

If I do 

`DEST=/mnt/ssd/backups/duplicity/temp/ LOGFILE=/tmp/duplicity/ ROOT=/home/le/temp/restore/ duplicity-backup -help`

it looks quite promising. At the end of the output I am getting

```
  CURRENT SCRIPT VARIABLES:
  ========================
    DEST (backup destination)       = /mnt/ssd/backups/duplicity/temp/
    INCLIST (directories included)  = 
    EXCLIST (directories excluded)  = 
    ROOT (root directory of backup) = /home/le/temp/restore/
    LOGFILE (log file path)         = /tmp/duplicity/
```

It looks like I have a minimal configuration.
However, then trying to restore with:

`DEST=/mnt/ssd/backups/duplicity/temp/ LOGFILE=/tmp/duplicity/ ROOT=/home/le/temp/ duplicity-backup --restore`

fails with a

`ERROR: can't find config file! (duplicity-backup.conf)`

Why do I need a config file if I already set the important variables?

Now, even more confusing, putting the three variables `DEST`, `LOGFILE` and `ROOT` into a config file, I am getting the following output:
```
  CURRENT SCRIPT VARIABLES:
  ========================
    DEST (backup destination)       = 
    INCLIST (directories included)  = 
    EXCLIST (directories excluded)  = 
    ROOT (root directory of backup) = 
    LOGFILE (log file path)         = 
```

The restore then fails with:

```
[le@y730]: ~/temp/restore>$ duplicity-backup --restore
Log directory / is not writeable by this user: le
Aborting...
```

**Comment by zertrin** [comment]
Sorry, calling the script with variables set from en environment is not supported.

Please use a config file as documented. Not everything in the config file is required for restoring.

In the future, consider using the `--backup-script` feature to create a backup of your config.

see  https://github.com/zertrin/duplicity-backup.sh#usage-examples :

> Backup the script and gpg key in a encrypted tarfile (for safekeeping)
>
> duplicity-backup.sh [-c config_file] --backup-script

**Comment by mindrunner** [comment]
Thanks :)
