### ISSUE TITLE
The authorization mechanism you have provided is not supported

### ISSUE THREAD

**Issue by Zyles** [zertrin/duplicity-backup#191]
Custom config, running as root:

s3cmd configured. 

```
$ mv duplicity-backup.sh /usr/local/bin/duplicity-backup
$ duplicity-backup -f -n -c /etc/duplicity-backup/hostname.conf
```

```
 S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>732B7X1X2FC2872C</RequestId><HostId>qJ2xx3R51qxFwb8ll8LLGxxPvNvzm0jmji6HFSPki360s+E3kY+aKLD/nylhh9B6FKpoxE/Gq50=</HostId></Error>
```

What is this?

s3cmd works:

```
s3cmd put -r test s3://mybucket/private/
upload: 'test' -> 's3://mybucket/private/test'  [1 of 1]
 0 of 0     0% in    0s     0.00 B/s  done
```

```
Ubuntu 18.04
python2.7
```

**Comment by zertrin** [comment]
I don't know but that's likely not a problem with this script.

see https://github.com/zertrin/duplicity-backup.sh#duplicity-backupsh-is-not-duplicity:

> First, make sure you can perform a backup with duplicity without using this script. If you can't make the backup work with duplicity alone, the problem is probably concerning duplicity and not this script. If you manage to make a backup with duplicity alone but not with this script, then there is probably a problem with duplicity-backup.sh.

**Comment by n3b0r** [comment]
Exactly the same problem here. If it isn't a problem related to the script, a mini how-to with Amazon S3 will be more than appreciated.

Thanks

**Comment by n3b0r** [comment]
I have some progress, I purged the python-boto package with

`
#apt purge python-boto
`

And then install through pip

`
#pip install boto
`

Now seems to work.

**Comment by Zyles** [comment]
Yes I confirmed it is a duplicity issue.

No solution that works for me yet.

**Comment by zertrin** [comment]
I will close this issue because the bug is not in this script. Moreover, I am not maintaining this project anymore.

Nevertheless, if you found a solution, please add a comment here to help other visitors that might find this thread from searching. 😉
