### ISSUE TITLE
Archive-dir option?

### ISSUE THREAD

**Issue by n3b0r** [zertrin/duplicity-backup#194]
Hi,

There is a specific option to configure the duplicity --archive-dir option in the config script or I have to add it into the extra options flag?

I'm trying to move the default cache folder from /root/.cache to another directory.

This is my need: https://serverfault.com/a/931846

Thanks,

**Comment by zertrin** [comment]
Yes, anything that is not covered by the example config file and that can be configured as an argument to duplicity can (and should) go in the extra option variable, aka `STATIC_OPTIONS`.
