### ISSUE TITLE
[Feature Request] Send mails only on failure

### ISSUE THREAD

**Issue by Rtone** [zertrin/duplicity-backup#46]
Mail notification works great but it could be useful to receive such alerts only when a backup process fails.

**Comment by jstoiko** [comment]
+1

**Comment by JavierMartinz** [comment]
+1

**Comment by zertrin** [comment]
A simpler solution (without using a trap) has been implemented in the pull request #105 
The implementation has not been thoroughly tested, please report any bug by opening new issues. In the meantime I'm closing this one.
