### ISSUE TITLE
Unwanted dirs showing up failing in output

### ISSUE THREAD

**Issue by ilium007** [zertrin/duplicity-backup#55]
I have the ROOT set up as "/"

and the INCLIST set up as:

INCLIST=(  "/etc/nginx" \
           "/etc/php5" \
           "/home/ilium007" \
           "/apps" \
        )
#

When the backup runs I see these errors:

Last full backup date: Sun Aug 18 15:26:54 2013
Error accessing possibly locked file /etc/.pwd.lock
Error accessing possibly locked file /etc/at.deny
Error accessing possibly locked file /etc/fuse.conf
Error accessing possibly locked file /etc/group-
Error accessing possibly locked file /etc/gshadow
Error accessing possibly locked file /etc/gshadow-
Error accessing possibly locked file /etc/passwd-
Error accessing possibly locked file /etc/shadow
Error accessing possibly locked file /etc/shadow-
Error accessing possibly locked file /etc/sudoers
Error accessing possibly locked file /lost+found
Error accessing possibly locked file /root
Error accessing possibly locked file /swapfile

I have asked for none of these files to be backed up yet there are 13 errors.

**Comment by zertrin** [comment]
By lack of activity I'm closing this issue. If you think there is still a bug somewhere feel free to reopen the issue and provide some more information.
