### ISSUE TITLE
/usr/bin/mailx: invalid option -- 'r'

### ISSUE THREAD

**Issue by smu** [zertrin/duplicity-backup#80]
Using the lasted revision on Debian wheezy I get the following error message:

```
## ./duplicity-backup.sh -c config
USAGE:
    duplicity-backup.sh [options]

  Options:
    -c, --config CONFIG_FILE   specify the config file to use

    -b, --backup               runs an incremental backup
    -f, --full                 forces a full backup
    -v, --verify               verifies the backup
    -l, --list-current-files   lists the files currently backed up in the archive
    -s, --collection-status    show all the backup sets in the archive

        --restore [PATH]       restores the entire backup to [path]
        --restore-file [FILE_TO_RESTORE] [DESTINATION]
                               restore a specific file
        --restore-dir [DIR_TO_RESTORE] [DESTINATION]
                               restore a specific directory

    -t, --time TIME            specify the time from which to restore or list files
                               (see duplicity man page for the format)

    --backup-script            automatically backup the script and secret key(s) to
                               the current working directory

    -n, --dry-run              perform a trial run with no changes made
    -d, --debug                echo duplicity commands to logfile

  CURRENT SCRIPT VARIABLES:
  ========================
    DEST (backup destination)       = XXXXX
    INCLIST (directories included)  = XXXXX
    EXCLIST (directories excluded)  = 
    ROOT (root directory of backup) = /
    LOGFILE (log file path)         = /root/new_backup/duplicity-2015-01-20_13-26.txt


/usr/bin/mailx: invalid option -- 'r'
usage: mailx [-dEIinv] [-a header] [-b bcc-addr] [-c cc-addr] [-s subject] to-addr ...
       mailx [-dEIiNnv] -f [name]
       mailx [-dEIiNnv] [-u user]
```

When I change MAIL to "mail" everything works fine.

**Comment by zertrin** [comment]
Hi, thanks for this bug report.

To better understand what is going on there, could you provide the output of the following command:

    dpkg -S $(readlink -e $(which mailx))

It will try to determine the package which is currently responsible for managing the mailx binary.
On my systems (debian jessie and debian wheezy) the output is:

    bsd-mailx: /usr/bin/bsd-mailx

**Comment by smu** [comment]
Thanks for the quick reply.

Same here:

% dpkg -S $(readlink -e $(which mailx))

bsd-mailx: /usr/bin/bsd-mailx

% lsb_release -a
No LSB modules are available.
Distributor ID:    Debian
Description:   Debian GNU/Linux 7.8 (wheezy)
Release:   7.8
Codename:  wheezy

**Comment by smu** [comment]
I tried it again with ```set -x``` right before the ```mailx``` command.
The following is executed:
```/usr/bin/mailx -s 'dub tests' -r MAILFROM MAILTO```
and results in:
```
/usr/bin/mailx: invalid option -- 'r'
usage: mailx [-dEIinv] [-a header] [-b bcc-addr] [-c cc-addr] [-s subject] to-addr ...
       mailx [-dEIiNnv] -f [name]
       mailx [-dEIiNnv] [-u user]
```

You don't get this error on your debian wheezy installation?

**Comment by zertrin** [comment]
Thanks for the infos!

To be honest I am not using the mail functionality of the script myself on my production server. I'll have a closer look and test properly as soon as possible.

**Comment by amnesiemaniac** [comment]
Hey. Had the same error, fixed it by installing heirloom-mailx.

**Comment by zertrin** [comment]
Now that you are saying it, on my previous server (wheezy) I had `heirloom-mailx`, I migrated recently to new hardware and started directly with Debian Jessie where `bsd-mailx` is used to handle the `mailx` command.

I haven't had the time to investigate further yet but it's still high in my todo list ;)

**Comment by zertrin** [comment]
Once again thanks for reporting the issue and sorry for the very long delay before being able to investigate further.

I finally rewrote the entire email sending section of the script (see pull request #120), thus I'm closing this issue which is based on the old version of the code.

I welcome any feedback, feel free to test and open a new issue if any problem arise with the rework.
