### ISSUE TITLE
"Email couldn't be sent. 'sendmail' not available."

### ISSUE THREAD

**Issue by MrJamesEllis** [zertrin/duplicity-backup#88]
Hi there, it seems that duplicity-backup can't find sendmail on the server it's set up on. At the end of each duplicity-backup log I see:

```
---------    END DUPLICITY-BACKUP SCRIPT    ---------

Email couldn't be sent. 'sendmail' not available.
Removing lock. Exit code: 0
```

The backup script runs via a Cron job under user root, similar to the example in the docs:

```
30 23 * * * cd /path/to/duplicity-backup; ./duplicity-backup.sh -c /path/to/duplicity-backup.conf -b
```

Checking through the `duplicity-backup.sh` script I see the following:

```
MAILCMD=$(which $MAIL)
      if [ ! -x "$MAILCMD" ]; then
          echo -e "Email couldn't be sent. '${MAIL}' not available." >> ${LOGFILE}
      else
```

$MAIL is set to `sendmail` in the conf file:

```
MAIL="sendmail"
```

If I run `which sendmail` on a shelll as any user, including root, I see:

```
/usr/sbin/sendmail
```

I cobbled together a script test.sh like so:

```
#!/bin/bash
MAIL="sendmail"
MAILCMD=$(which $MAIL)

echo "MAIL is '${MAIL}'"
echo "MAILCMD is '${MAILCMD}'"

if [ ! -x "$MAILCMD" ]; then
        echo "Email can't be sent. '${MAIL}' not available."
else
        echo "Email can be sent. '${MAIL}' available."
fi
```

which, when run as a user and root both output:

$ ./test.sh
MAIL is 'sendmail'
MAILCMD is '/usr/sbin/sendmail'
Email can be sent. 'sendmail' available.

The only difference I see between my script and duplicity-backup.sh is the shebang line `#!/usr/bin/env bash`
I switched my script to that and the output still shows that sendmail is available.

Fairly puzzling as to why this would happen. If I try `mailx` then an error appears:
```
/usr/bin/mailx: invalid option -- 'r'
```

Which shows to me that a 'which mailx' is returning the path to mailx (i.e it's executing the 'else' part of the MAILCMD test).

I'll keep digging but if you have any ideas on this it would help greatly.
This is running on a Ubuntu 14.04 server.

Thanks
James

**Comment by MrJamesEllis** [comment]
Aha, it would appear that cron doesn't like the shebang line `#!/usr/bin/env bash` in `duplicity_backup.sh` I changed it to `#!/bin/bash` and the script now finds sendmail OK and sends out the email once the backup job has run.

I'll close this issue but feel free to reopen if required.

**Comment by Gizmo091** [comment]
Thx a lot for your trick. Save my day
