### ISSUE TITLE
Destination Disk Use Information: unsupported type backend

### ISSUE THREAD

**Issue by almsta** [zertrin/duplicity-backup#93]
Hi!
I'm getting the following error (?) in my log, using scp://

    ---------[ Destination Disk Use Information ]--------
    unsupported on  s: type backend

Also changing to sftp (for example) leads to this error.

**Comment by zertrin** [comment]
This isn't an error, just an informative message. This functionality is only available for some backends (SSH, file, Amazon S3 and Google Cloud). See https://github.com/zertrin/duplicity-backup/blob/master/duplicity-backup.sh#L422

Maybe we could make the message a bit more explicit about this fact and name explicitly the backends for which this is available.

**Comment by zertrin** [comment]
Done, should be clearer now :)
