### ISSUE TITLE
Email not sent (which: no sendmail in (/usr/bin:/bin))

### ISSUE THREAD

**Issue by dcmwai** [zertrin/duplicity-backup#97]
Hello there, this is a nice script.
would like your advise to understand where to check or debug this issue...

Thank you

**Comment by dcmwai** [comment]
Sorry, I got the error...

which: no sendmail in (/usr/bin:/bin)

my server show 
which sendmail
/usr/sbin/sendmail

Any suggestion?

**Comment by zertrin** [comment]
Looks like a PATH issue. The PATH used in crontabs can be different that the one of the one you're using when logged in.

I can't help much further, you need to check the specifics of your distribution concerning the PATH setting in crontabs.

Alternatively, writing a little bash script which sets the correct path prior to launching duplicity.backup.sh, and using this script in the crontab may be a workaround.

Something like (disclaimer, not tested, this is just to convey the idea)
```
#!/bin/bash
PATH=$PATH:/usr/sbin
/path/to/duplicity-backup.sh -c /path/to/config/file --backup
```

**Comment by dcmwai** [comment]
Thank zertrin,

Yep, that fixed the issue.
Now only I know that which will only list files under PATH...
so 
MAILCMD=$(which $MAIL)

Can't fix this.

**Comment by zertrin** [comment]
Thanks for the feedback. I'll close this issue then :)
